version: '3'
services:
  optimists-backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - API_SERVER_PORT=3000
      - MYSQL_DATABASE_URL=mysql://root:password@optimists-mysql/cs24_p2_optimists
      - CLOUDINARY_CLOUD_NAME=ss
      - CLOUDINARY_API_KEY=ss
      - CLOUDINARY_API_SECRET=ss
      - COOKIE_SECRET=9c1a60e5b9fd0b9763c8df7a81e2e32d
      - ACCESS_TOKEN=access-token
      - JWT_ACCESS_TOKEN_EXPIRY=6000000000
      - JWT_SECRET=f7a30d6b8e03626b78db0e6e958acf57
      - NODEMAILER_SERVICE=gmail
      - NODEMAILER_USER=jubaer@gmail.com
      - NODEMAILER_PASSWORD=password
      - ADMIN_PASSWORD=igloo1119
      - ADMIN_EMAIL=admin@gmail.com
    depends_on:
      - optimists-mysql
    # restert: always

  optimists-mysql: 
    image: mysql:latest
    ports:
        - "3307:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=cs24_p2_optimists
    volumes:
      - optimists-database-volume:/var/lib/mysql
    # restart: always

  optimists-frontend:
    build: ./frontend
    ports:
      - "8080:8080"

volumes:
  optimists-database-volume: