import { IUsers } from "@/models/Users";

export const dummyUsers: IUsers[] = [
  {
    name: "John Doe",
    userName: "john_doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    role: "Admin",
    userId: "1",
    createdAt: new Date("2022-03-25"),
  },
  {
    name: "Jane Smith",
    userName: "jane_smith",
    email: "jane.smith@example.com",
    phone: "+1987654321",
    role: "STS Manager",
    userId: "2",
    createdAt: new Date("2022-03-25"),
  },
  {
    name: "Alice Johnson",
    userName: "alice_johnson",
    email: "alice.johnson@example.com",
    phone: "+1122334455",
    role: "Unassigned",
    userId: "3",
    createdAt: new Date("2022-03-26"),
  },
  {
    name: "Bob Brown",
    userName: "bob_brown",
    email: "bob.brown@example.com",
    phone: "+1765432987",
    role: "Landfil Manager",
    userId: "4",
    createdAt: new Date("2022-03-25"),
  },
  {
    name: "Emily Davis",
    userName: "emily_davis",
    email: "emily.davis@example.com",
    phone: "+1987234567",
    role: "Unassigned",
    userId: "5",
    createdAt: new Date("2022-03-25"),
  },
  // Add 5 more entries
  {
    name: "Michael Johnson",
    userName: "michael_johnson",
    email: "michael.johnson@example.com",
    phone: "+1122334455",
    role: "Admin",
    userId: "6",
    createdAt: new Date("2022-03-26"),
  },
  {
    name: "Jessica Brown",
    userName: "jessica_brown",
    email: "jessica.brown@example.com",
    phone: "+1765432987",
    role: "Manager",
    userId: "7",
    createdAt: new Date("2022-03-25"),
  },
  {
    name: "David Smith",
    userName: "david_smith",
    email: "david.smith@example.com",
    phone: "+1987234567",
    role: "Developer",
    userId: "8",
    createdAt: new Date("2022-03-25"),
  },
  {
    name: "Sarah Davis",
    userName: "sarah_davis",
    email: "sarah.davis@example.com",
    phone: "+1987654321",
    role: "Designer",
    userId: "9",
    createdAt: new Date("2022-03-25"),
  },
  {
    name: "Daniel Wilson",
    userName: "daniel_wilson",
    email: "daniel.wilson@example.com",
    phone: "+1234567890",
    role: "Tester",
    userId: "10",
    createdAt: new Date("2022-03-25"),
  },
];
